#
# This file is used for local development/builds
# Need to keep this in sync with .drone.ci.yml
#

kind: pipeline
type: exec
name: default-amd64

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/github.com/leodotcloud/swiss-army-knife

volumes:
  - name: docker
    host:
      path: /var/lib/docker
  - name: docker_socket
    host:
      path: /var/run/docker.sock

steps:
  - name: version
    image: golang:1.13.9-buster
    commands:
      - ./scripts/version

  - name: lint
    image: golangci/golangci-lint:v1.24.0
    commands:
      - ./scripts/lint

  - name: test
    image: golang:1.13.9-buster
    environment:
      CGO_ENABLED: 0
      GOFLAGS: -mod=vendor
    commands:
      - . ./version.env
      - ./scripts/test

  - name: build
    image: golang:1.13.9-buster
    environment:
      CGO_ENABLED: 0
      GOFLAGS: -mod=vendor
    commands:
      - . ./version.env
      - ./scripts/build

  - name: publish
    image: plugins/docker
    volumes:
      - name: docker
        path: /var/lib/docker
      - name: docker_socket
        path: /var/run/docker.sock
    settings:
      username:
        from_secret: DOCKERHUB_USERNAME
      password:
        from_secret: DOCKERHUB_PASSWORD
      repo: leodotcloud/swiss-army-knife
      tags:
        - dev
      dockerfile: package/Dockerfile
      dry_run: true
