#
# This file is used for running on CI server
# Need to keep this in sync with .drone.yml
#

kind: pipeline
type: docker
name: default-amd64

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    - main

workspace:
  base: /go
  path: src/github.com/leodotcloud/swiss-army-knife

volumes:
  - name: k3s-run
    temp:
      medium: memory
  - name: k3s-var-run
    temp:
      medium: memory

steps:
  - name: version
    image: golang:1.13.9-buster
    commands:
      - ./scripts/version

  - name: lint
    image: golangci/golangci-lint:v1.24.0
    commands:
      - ./scripts/lint

  - name: test
    image: golang:1.13.9-buster
    environment:
      CGO_ENABLED: 0
      GOFLAGS: -mod=vendor
    commands:
      - . ./version.env
      - ./scripts/test

  - name: build
    image: golang:1.13.9-buster
    environment:
      CGO_ENABLED: 0
      GOFLAGS: -mod=vendor
    commands:
      - . ./version.env
      - ./scripts/build

  - name: test-deployment-on-k3s
    image: rancher/k3s:latest
    privileged: true
    volumes:
      - name: k3s-run
        path: /run
      - name: k3s-var-run
        path: /var/run
    commands:
      - pwd
      - ls
      - ls -l scripts
      - sh scripts/test-on-k3s.sh

  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB_USERNAME
      password:
        from_secret: DOCKERHUB_PASSWORD
      repo: leodotcloud/swiss-army-knife
      dockerfile: package/Dockerfile
      tags:
        - latest
        - ${DRONE_TAG}
    when:
      branch:
        - main
      event:
        - tag

