#!/bin/bash
set -ex

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
[ "$(uname)" != "Darwin" ] && [ "${OS}" != "windows" ] && LINKFLAGS="-linkmode external -extldflags -static -s"

OUTPUT=bin/swiss-army-knife
if [ "${OS}" == "windows" ]; then
    OUTPUT=bin/swiss-army-knife.exe
fi

GOOS=${OS} GOARCH=${ARCH} go build -ldflags "-X main.VERSION=$VERSION $LINKFLAGS" -o ${OUTPUT}
