#!/bin/sh

set -e

# This logic is to make sure, we can build directly from CLI
if [ -z ${VERSION_SET+x} ];then
    source $(dirname $0)/version
fi

cd $(dirname $0)/..

[ "$(uname)" != "Darwin" ] && [ "${OS}" != "windows" ] && LINKFLAGS=""

OUTPUT=swiss-army-knife
if [ "${OS}" = "windows" ]; then
    OUTPUT=swiss-army-knife.exe
fi
GOOS=${OS} GOARCH=${ARCH} go build -ldflags "-X main.VERSION=$VERSION $LINKFLAGS" -o ${OUTPUT}
