#!/bin/sh

set -e

# This logic is to make sure, we can build directly from CLI
if [ -z ${VERSION_SET+x} ];then
    source $(dirname $0)/version
fi

cd $(dirname $0)/..

echo Running tests

GOOS=${OS} GOARCH=${ARCH} go test -cover -tags=test
