name: swiss army knife ci

on:
  release:
    types:
      - published
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
  pull_request:
    types:
      - synchronize
      - ready_for_review

permissions:
  issues: write
  contents: write
  packages: write
  pull-requests: write

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  build:
    uses: ./.github/workflows/build-app.yml
    needs:
      - lint
      - test
    secrets:
      dockerhub_token: ${{ (github.ref_name == 'main' || (github.event_name == 'release' && github.event.action == 'published')) && secrets.DOCKERHUB_TOKEN || '' }}
