name: linting

on:
  workflow_call:

jobs:
  linting:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.13.9'

      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.28.3
          skip-go-installation: true
