name: testing

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.13'

      - name: install deps
        run: go mod tidy && go mod vendor

      - name: run test
        run: bash scripts/test
