name: version

on:
  workflow_call:
    outputs:
      version:
        value: ${{ jobs.get-version.outputs.version }}
      image_version:
        value: ${{ jobs.get-version.outputs.image_version }}

jobs:
  get-version:
    runs-on: ubuntu-22.04

    outputs:
      version: ${{ steps.get_version.outputs.version }}
      image_version: ${{ steps.get_version.outputs.image_version }}

    steps:
      - uses: actions/checkout@v4

      - name: generate version.env
        run: ./scripts/version

      - name: output version variables to github output
        id: get_version
        run: sed 's/export //g' version.env | awk '{ print tolower($1) }' | tee -a $GITHUB_OUTPUT
